#!/usr/bin/env bun
/*
 * Copyright 2026 Jason Dillon
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Stamps src/build-info.ts with git metadata.
 * Run via: bun run build:info
 * Pass --release to mark as a release build (clean semver, no -dev suffix).
 */

import { $ } from "bun";

const release = process.argv.includes("--release");
const sha = (await $`git rev-parse --short HEAD`.text()).trim();
const branch = (await $`git rev-parse --abbrev-ref HEAD`.text()).trim();
const timestamp = new Date().toISOString();

const content = `// Auto-generated by scripts/stamp-build-info.ts — do not edit
export const BUILD_RELEASE = ${release};
export const BUILD_SHA = ${JSON.stringify(sha)};
export const BUILD_BRANCH = ${JSON.stringify(branch)};
export const BUILD_TIMESTAMP = ${JSON.stringify(timestamp)};
`;

import { resolve } from "path";
const outPath = resolve(import.meta.dir, "../src/build-info.ts");
await Bun.write(outPath, content);
console.log(`Stamped build-info: ${release ? "release" : "dev"} ${branch}@${sha} (${timestamp})`);
